#!/usr/bin/env python

# LICENSE DISCLAIMER
# This file has been generated by EvoMaster.
# The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
# This generated software (i.e., the test suite in this file) can be freely used, modified, 
# and distributed as you see fit without any restrictions.
import json
import unittest
import requests
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *


#  This file was automatically generated by EvoMaster on 2026-01-18T03:26:13.489515300-06:00[America/Chicago]
#  
#  The generated test suite contains 49 tests
#  
#  Covered targets: 228
#  
#  Used time: 10h 1m 53s
#  
#  Needed budget for current results: 94%
#  
#  This file contains test cases that are likely to indicate faults.
class EvoMaster_faults_Test(unittest.TestCase):

    
    baseUrlOfSut = "http://129.62.148.112:32677"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (500) GET:/api/v1/travel2service/admin_trip
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_0_get_on_travel2service_admin_trip_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/travel2service/admin_trip",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/travel2service/admin_trip"
    
    
    # Calls:
    # (500) GET:/api/v1/travelservice/admin_trip
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_1_get_on_travelservice_admin_trip_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/travelservice/admin_trip",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/travelservice/admin_trip"
    
    
    # Calls:
    # (500) GET:/api/v1/adminuserservice/users
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_2_get_on_users_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/adminuserservice/users",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/adminuserservice/users"
    
    
    # Calls:
    # (500) GET:/api/v1/admintravelservice/admintravel
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_3_get_on_admintravel_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/admintravelservice/admintravel",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/admintravelservice/admintravel"
    
    
    # Calls:
    # (500) POST:/api/v1/waitorderservice/order
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_4_post_on_waitorderservice_order_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"to\": \"trainticket_alert@163.com\", " + \
            " \"tripId\": \"\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/waitorderservice/order",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/waitorderservice/order"
    
    
    # Calls:
    # (500) POST:/api/v1/travel2service/trips
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_5_post_on_travel2service_trips_causes500_internalServerError(self):
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"loginId\": \"JC\", " + \
            " \"routeId\": \"4bDIs4XAiUR1Ix5\", " + \
            " \"startTime\": \"_G16P_ZfdWP6adt\", " + \
            " \"stationsName\": \"yPfwdJ1FG\", " + \
            " \"terminalStationName\": \"X\", " + \
            " \"tripId\": \"Ujf1UWiz9si_\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/travel2service/trips",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/travel2service/trips"
    
    
    # Calls:
    # (500) POST:/api/v1/travel2service/trip_detail
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_6_post_on_travel2service_trip_detail_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"from\": \"k\", " + \
            " \"to\": \"CcvV9717mfvHenRx\", " + \
            " \"travelDate\": \"i9OlXaf\", " + \
            " \"tripId\": \"\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/travel2service/trip_detail",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/travel2service/trip_detail"
    
    
    # Calls:
    # (500) POST:/api/v1/travelservice/trips
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_7_post_on_travelservice_trips_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"loginId\": \"W6BTN\", " + \
            " \"startTime\": \"usFDBnhahYjD0H\", " + \
            " \"stationsName\": \"L_YTb3srS2\", " + \
            " \"terminalStationName\": \"ggHh\", " + \
            " \"tripId\": \"5pFY5WSNXfRvq\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/travelservice/trips",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/travelservice/trips"
    
    
    # Calls:
    # (500) POST:/api/v1/travelservice/trip_detail
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_8_post_on_travelservice_trip_detail_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"to\": \"trainticket_update@163.com\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/travelservice/trip_detail",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/travelservice/trip_detail"
    
    
    # Calls:
    # (500) POST:/api/v1/routeservice/routes
    # Found 1 potential fault of type-code 100
    # Using 1 example:
    #   (-) BODY -> Shanghai,Hangzhou,Nanjing,Beijing
    @timeout_decorator.timeout(60)
    def test_9_post_on_routes_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"id\": \"trainticket_notice@163.com\", " + \
            " \"startStation\": \"shanghaihongqiao\", " + \
            " \"stationList\": \"Shanghai,Hangzhou,Nanjing,Beijing\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/routeservice/routes",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/routeservice/routes"
    
    
    # Calls:
    # (500) POST:/api/v1/preserveservice/preserve
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_10_post_on_preserve_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"assurance\": -510393680, " + \
            " \"consigneeName\": \"UtNfLALnBij7Lzw\", " + \
            " \"contactsId\": \"26732ef6-2936-4ce8-8d06-090aaa3ddcbe\", " + \
            " \"date\": \"acc-234567\", " + \
            " \"foodName\": \"iFdzUk\", " + \
            " \"foodPrice\": 0.9405252691422064, " + \
            " \"from\": \"shanghai\", " + \
            " \"loginToken\": \"trainticket_alert@163.com\", " + \
            " \"seatType\": 561, " + \
            " \"stationName\": \"taiyuan\", " + \
            " \"storeName\": \"McDonald\u0027s\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/preserveservice/preserve",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/preserveservice/preserve"
    
    
    # Calls:
    # (500) POST:/api/v1/preserveotherservice/preserveOther
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_11_post_on_preserveOther_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"accountId\": \"acc-789012\", " + \
            " \"assurance\": 669, " + \
            " \"consigneeWeight\": 0.26223804716036325, " + \
            " \"contactsId\": \"8b56d474-6501-4251-96f6-d92aac6f54b6\", " + \
            " \"date\": \"Contacts_Two\", " + \
            " \"foodName\": \"Big Mac\", " + \
            " \"foodPrice\": 0.919632228941397, " + \
            " \"foodType\": 890, " + \
            " \"from\": \"7DnQhGkBc6jwchm\", " + \
            " \"handleDate\": \"\", " + \
            " \"loginToken\": \"Hangzhou\", " + \
            " \"stationName\": \"beijing\", " + \
            " \"storeName\": \"Roman Holiday\", " + \
            " \"to\": \" Shanghai\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/preserveotherservice/preserveOther",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/preserveotherservice/preserveOther"
    
    
    # Calls:
    # (500) POST:/api/v1/orderservice/order
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_12_post_on_orderservice_order_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"accountId\": \"acc-901234\", " + \
            " \"boughtDate\": \"2026-01-15\", " + \
            " \"coachNumber\": 105, " + \
            " \"documentType\": 641, " + \
            " \"id\": \"LYEGLDa\", " + \
            " \"price\": \"0.914669216496542\", " + \
            " \"status\": 4, " + \
            " \"to\": \"Snh4leEofqP\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/orderservice/order",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/orderservice/order"
    
    
    # Calls:
    # (500) POST:/api/v1/foodservice/createOrderBatch
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_13_post_on_createOrderBatch_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " [ " + \
            " { " + \
            " \"foodName\": \"I\", " + \
            " \"foodType\": 428, " + \
            " \"id\": \"\", " + \
            " \"price\": 0.07068773211365453 " + \
            " }, " + \
            " { " + \
            " \"foodType\": 684, " + \
            " \"id\": \"8oxiU\", " + \
            " \"orderId\": \"io9fSJ2p6leqI\", " + \
            " \"price\": 0.6814256986372066 " + \
            " } " + \
            " ] "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/foodservice/createOrderBatch",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/foodservice/createOrderBatch"
    
    
    # Calls:
    # (500) POST:/api/v1/fooddeliveryservice/orders
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_14_post_on_orders_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"createdTime\": \"6\", " + \
            " \"deliveryFee\": 0.24276460029749114, " + \
            " \"foodList\": [ " + \
            " {}, " + \
            " {} " + \
            " ], " + \
            " \"id\": \"UGOM6G\", " + \
            " \"seatNo\": 160, " + \
            " \"stationFoodStoreId\": \"MRPW\", " + \
            " \"tripId\": \"NVah\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/fooddeliveryservice/orders",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/fooddeliveryservice/orders"
    
    
    # Calls:
    # (500) POST:/api/v1/adminrouteservice/adminroute
    # Found 1 potential fault of type-code 100
    # Using 1 example:
    #   (-) BODY -> 12.5,8.2,15.7,22.1,5.9
    @timeout_decorator.timeout(60)
    def test_15_post_on_adminroute_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"distanceList\": \"12.5,8.2,15.7,22.1,5.9\", " + \
            " \"loginId\": \"Ic1jzGsQj03GhbS\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/adminrouteservice/adminroute",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/adminrouteservice/adminroute"
    
    
    # Calls:
    # (500) PUT:/api/v1/travel2service/trips
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_16_put_on_travel2service_trips_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"endTime\": \"g4ZujfxSQSM9\", " + \
            " \"routeId\": \"unQI1TfiSA1Jcq\", " + \
            " \"startStationName\": \"oZp9dcO\", " + \
            " \"startTime\": \"B5dwo\", " + \
            " \"terminalStationName\": \"ruqk\", " + \
            " \"trainTypeName\": \"G6pKWUpogdn\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .put(self.baseUrlOfSut + "/api/v1/travel2service/trips",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/travel2service/trips"
    
    
    # Calls:
    # (500) PUT:/api/v1/travelservice/trips
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_17_put_on_travelservice_trips_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"endTime\": \"vaD\", " + \
            " \"loginId\": \"\", " + \
            " \"terminalStationName\": \"Mb\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .put(self.baseUrlOfSut + "/api/v1/travelservice/trips",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/travelservice/trips"
    
    
    # Calls:
    # (500) PUT:/api/v1/orderservice/order
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_18_put_on_order_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"boughtDate\": \"Iz9nRPH\", " + \
            " \"contactsDocumentNumber\": \"\", " + \
            " \"seatNumber\": \"8Ef3pY\", " + \
            " \"to\": \"So\", " + \
            " \"trainNumber\": \"VOoyjy9KffTdu0q\", " + \
            " \"travelDate\": \"3OiwI5UyBgxDEh\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .put(self.baseUrlOfSut + "/api/v1/orderservice/order",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/orderservice/order"
    
    
    # Calls:
    # (500) PUT:/api/v1/orderOtherService/orderOther
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_19_put_on_orderOther_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"accountId\": \"acc-345678\", " + \
            " \"coachNumber\": 123, " + \
            " \"contactsDocumentNumber\": \"\", " + \
            " \"documentType\": 352, " + \
            " \"from\": \"Qq\", " + \
            " \"price\": \"rr\", " + \
            " \"seatClass\": 4, " + \
            " \"status\": 289, " + \
            " \"trainNumber\": \"D5678\", " + \
            " \"travelDate\": \"OURlXlRjPxjvT\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .put(self.baseUrlOfSut + "/api/v1/orderOtherService/orderOther",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/orderOtherService/orderOther"
    
    
    # Calls:
    # (500) PUT:/api/v1/foodservice/orders
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_20_put_on_orders_causes500_internalServerError(self):
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"foodName\": \"sGjE1jU2VFeVV\", " + \
            " \"orderId\": \"kmk\", " + \
            " \"stationName\": \"\", " + \
            " \"storeName\": \"\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .put(self.baseUrlOfSut + "/api/v1/foodservice/orders",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/foodservice/orders"
    
    
    # Calls:
    # (500) PUT:/api/v1/contactservice/contacts
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_21_put_on_contactservice_contacts_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"documentNumber\": \"JktYF_U9\", " + \
            " \"name\": \"zrMcWAzNF8\", " + \
            " \"phoneNumber\": \"9ce2H\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .put(self.baseUrlOfSut + "/api/v1/contactservice/contacts",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/contactservice/contacts"
    
    
    # Calls:
    # (500) GET:/api/v1/stationfoodservice/stationfoodstores/{stationId}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_22_get_on_stationfoodstor_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/stationfoodservice/stationfoodstores/Pk_ZhnjSf2nUbC",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/stationfoodservice/stationfoodstores/Pk_ZhnjSf2nUbC"
    
    
    # Calls:
    # (500) GET:/api/v1/inside_pay_service/inside_payment/account
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_23_get_on_inside_payment_account_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/inside_pay_service/inside_payment/account",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/inside_pay_service/inside_payment/account"
    
    
    # Calls:
    # (500) GET:/api/v1/foodservice/orders/{orderId}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_24_get_on_foodservice_order_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/foodservice/orders/UDvQR",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/foodservice/orders/UDvQR"
    
    
    # Calls:
    # (500) GET:/api/v1/adminbasicservice/adminbasic/contacts
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_25_get_on_contacts_causes500_internalServerError(self):
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/contacts",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/adminbasicservice/adminbasic/contacts"
    
    
    # Calls:
    # (500) POST:/api/v1/userservice/users/register
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_26_post_on_register_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"gender\": 212, " + \
            " \"userId\": \"1b4b593a-5f2a-456b-8623-4b23a883de0c\", " + \
            " \"userName\": \"FQit4NIGe0vFPA\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/userservice/users/register",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/userservice/users/register"
    
    
    # Calls:
    # (500) POST:/api/v1/travel2service/trips/left
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_27_post_on_left_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"departureTime\": \"2048-04-26\", " + \
            " \"endPlace\": \"kXh3wxAge_\", " + \
            " \"startPlace\": \"Xl_\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/travel2service/trips/left",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/travel2service/trips/left"
    
    
    # Calls:
    # (500) POST:/api/v1/travelplanservice/travelPlan/transferResult
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_28_post_on_transferResult_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"startStation\": \"\", " + \
            " \"trainType\": \"Jhlybn6uAfaSDxv\", " + \
            " \"viaStation\": \"X5AIbOyn\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/travelplanservice/travelPlan/transferResult",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/travelplanservice/travelPlan/transferResult"
    
    
    # Calls:
    # (500) POST:/api/v1/priceservice/prices/byRouteIdsAndTrainTypes
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_29_post_on_byRouteIdsAndTrainTypes_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " [ " + \
            " \"1zL0T2d\", " + \
            " \"Q8Cu\", " + \
            " \"kJkqIMPejZ\" " + \
            " ] "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/priceservice/prices/byRouteIdsAndTrainTypes",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/priceservice/prices/byRouteIdsAndTrainTypes"
    
    
    # Calls:
    # (500) POST:/api/v1/orderservice/order/tickets
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_30_post_on_order_tickets_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"seatType\": 0, " + \
            " \"startStation\": \"shanghaihongqiao\", " + \
            " \"stations\": [ " + \
            " \"suzhou\", " + \
            " \"shijiazhuang\" " + \
            " ], " + \
            " \"trainNumber\": \"G1234\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/orderservice/order/tickets",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/orderservice/order/tickets"
    
    
    # Calls:
    # (500) POST:/api/v1/orderOtherService/orderOther/tickets
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_31_post_on_orderOther_tickets_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"totalNum\": 330, " + \
            " \"travelDate\": \"2026-01-15\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/orderOtherService/orderOther/tickets",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/orderOtherService/orderOther/tickets"
    
    
    # Calls:
    # (500) POST:/api/v1/basicservice/basic/travels
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_32_post_on_travels_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " [ " + \
            " { " + \
            " \"trip\": {} " + \
            " }, " + \
            " { " + \
            " \"departureTime\": \"sNlJ\", " + \
            " \"endPlace\": \"_2y_\", " + \
            " \"startPlace\": \"eHuAH\" " + \
            " }, " + \
            " { " + \
            " \"startPlace\": \"pz2\" " + \
            " }, " + \
            " { " + \
            " \"departureTime\": \"oVkZtaTob\", " + \
            " \"trip\": {} " + \
            " } " + \
            " ] "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/basicservice/basic/travels",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/basicservice/basic/travels"
    
    
    # Calls:
    # (500) POST:/api/v1/basicservice/basic/travel
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_33_post_on_travel_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"endPlace\": \"SdNpCu\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/api/v1/basicservice/basic/travel",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/basicservice/basic/travel"
    
    
    # Calls:
    # (500) PUT:/api/v1/fooddeliveryservice/orders/tripid
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_34_put_on_tripid_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"tripId\": \"urD9CZEc52eL\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .put(self.baseUrlOfSut + "/api/v1/fooddeliveryservice/orders/tripid",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/fooddeliveryservice/orders/tripid"
    
    
    # Calls:
    # (500) PUT:/api/v1/fooddeliveryservice/orders/seatno
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_35_put_on_seatno_causes500_internalServerError(self):
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"seatNo\": 671 " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .put(self.baseUrlOfSut + "/api/v1/fooddeliveryservice/orders/seatno",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/fooddeliveryservice/orders/seatno"
    
    
    # Calls:
    # (500) PUT:/api/v1/fooddeliveryservice/orders/dtime
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_36_put_on_dtime_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"deliveryTime\": \"\" " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .put(self.baseUrlOfSut + "/api/v1/fooddeliveryservice/orders/dtime",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/fooddeliveryservice/orders/dtime"
    
    
    # Calls:
    # (500) PUT:/api/v1/adminbasicservice/adminbasic/contacts
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_37_put_on_adminbasic_contacts_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers["content-type"] = "application/json"
        body = {}
        body = " {} "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .put(self.baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/contacts",
                    headers=headers, data=body, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/adminbasicservice/adminbasic/contacts"
    
    
    # Calls:
    # (500) DELETE:/api/v1/securityservice/securityConfigs/{id}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_38_delete_on_securityConfig_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/api/v1/securityservice/securityConfigs/YpRMtnnkYbXGg",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/securityservice/securityConfigs/YpRMtnnkYbXGg"
    
    
    # Calls:
    # (500) DELETE:/api/v1/orderservice/order/{orderId}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_39_delete_on_orderservice_order_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/api/v1/orderservice/order/UI96vGFWoHxHM",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/orderservice/order/UI96vGFWoHxHM"
    
    
    # Calls:
    # (500) DELETE:/api/v1/orderOtherService/orderOther/{orderId}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_40_delete_on_orderOth_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/api/v1/orderOtherService/orderOther/GhOkraw",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/orderOtherService/orderOther/GhOkraw"
    
    
    # Calls:
    # (500) DELETE:/api/v1/foodservice/orders/{orderId}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_41_delete_on_foodservice_order_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/api/v1/foodservice/orders/w7T6v5lmJIh",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/foodservice/orders/w7T6v5lmJIh"
    
    
    # Calls:
    # (500) DELETE:/api/v1/contactservice/contacts/{contactsId}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_42_delete_on_contactservice_contact_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/api/v1/contactservice/contacts/sPvsGyHiB",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/contactservice/contacts/sPvsGyHiB"
    
    
    # Calls:
    # (500) GET:/api/v1/consignservice/consigns/order/{id}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_43_get_on_consigns_order_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/consignservice/consigns/order/DpbHfv4",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/consignservice/consigns/order/DpbHfv4"
    
    
    # Calls:
    # (500) GET:/api/v1/consignservice/consigns/account/{id}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_44_get_on_consigns_account_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/consignservice/consigns/account/CsWkQM2qiYBhN",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/consignservice/consigns/account/CsWkQM2qiYBhN"
    
    
    # Calls:
    # (500) GET:/api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_45_get_on_consignpric_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/consignpriceservice/consignprice/gpXk3L/MjfwbJ4rvXB",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/consignpriceservice/consignprice/gpXk3L/MjfwbJ4rvXB"
    
    
    # Calls:
    # (500) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_46_delete_on_adminord_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/api/v1/adminorderservice/adminorder/L1Kt0EWEz3Av1O2Y/pfe3Zo4uJYQ",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/adminorderservice/adminorder/L1Kt0EWEz3Av1O2Y/pfe3Zo4uJYQ"
    
    
    # Calls:
    # (500) DELETE:/api/v1/adminbasicservice/adminbasic/contacts/{contactsId}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_47_delete_on_adminbasic_contact_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/contacts/XBlBAsj5PooW",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/adminbasicservice/adminbasic/contacts/XBlBAsj5PooW"
    
    
    # Calls:
    # (500) GET:/api/v1/foodservice/foods/{date}/{startStation}/{endStation}/{tripId}
    # Found 1 potential fault of type-code 100
    @timeout_decorator.timeout(60)
    def test_48_get_on_food_causes500_internalServerError(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = " { " + \
            " \"username\": \"admin\", " + \
            " \"password\": \"222222\" " + \
            " } "
        res_admin = requests \
                .post(self.baseUrlOfSut + "/api/v1/users/login", 
                    headers=headers, data=body, allow_redirects=False)
        token_admin =  res_admin.json()["data"]["token"]
        
        auth_admin = "Bearer " + token_admin
        
        # Fault100. HTTP Status 500. null.
        headers = {}
        headers["Authorization"] = auth_admin # admin
        headers['Accept'] = "*/*"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/api/v1/foodservice/foods/8a7480b99b9bc008019bcef1e03b00a6/w0znW/lglzrZ7F5/G1234",
                    headers=headers, timeout=60)
        
        assert res_0.status_code == 500
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == 500.0
        assert res_0.json()["error"] == "Internal Server Error"
        assert res_0.json()["message"] == ""
        assert res_0.json()["path"] == "/api/v1/foodservice/foods/8a7480b99b9bc008019bcef1e03b00a6/w0znW/lglzrZ7F5/G1234"


if __name__ == '__main__':
    unittest.main()
